"""
Django settings for DjangoEmumbaTrainingProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Self added code for getting secrets from .env file. Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)


# reading .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Now use environment variables like this:
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# SECURITY WARNING: keep the secret key used in production secret!
# This key is used for cryptographic signing. So, very imp in short
# If leaked: An attacker could forge session data, CSRF tokens, and reset tokens — leading to account takeovers or remote access.
# New secret key can be obtained by the following command:
#   python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = env('SECRET_KEY')


ALLOWED_HOSTS = []

# Telling our project that use this as the default user
AUTH_USER_MODEL = 'DjangoEmumbaTrainingApplication.OurUser'


# Email Configurations
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
# Our email credentials
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'Abdurrafay <abdur.rafay@emumba.com>'

# For media files storage
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Manually added, this is required for the authentication and login to work
REST_FRAMEWORK = {

    # This is for API pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'DjangoEmumbaTrainingApplication.authentication.CsrfExemptSessionAuthentication',  # ONLY FOR TESTING PURPOSE WITH POSTMAN, skips CSRF but still uses session login,
        'rest_framework.authentication.SessionAuthentication',  # for browser logins
        'rest_framework.authentication.BasicAuthentication',  # optional
        'rest_framework.authentication.TokenAuthentication',  # for token-based login
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # This makes every API endpoint require authentication by default, unless you explicitly override it with @permission_classes([AllowAny]).
    ]
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Manually added apps
    'rest_framework',
    'corsheaders',
    'DjangoEmumbaTrainingApplication.apps.DjangoemumbatrainingapplicationConfig',
]

# This will allow all to access our API, not recommended in Development environment
CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Manually added
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoEmumbaTrainingProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoEmumbaTrainingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Filled the below info using this from pgadmin, found in properties of our desired server
# host=localhost port=5432 dbname=UserTaskDataBase user=postgres password=xxxxxxx connect_timeout=10 sslmode=prefer
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'), # Your DataBase name
        'USER': env('DB_USER'), # Your DataBase User
        'PASSWORD': env('DB_PASSWORD'), # Your DataBase password
        'HOST': env('DB_HOST'), # IP or link where your DataBase is hosted
        'PORT': env('DB_PORT'), # Port where the postgres is running
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
