# Generated by Django 5.2 on 2025-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
