# Generated by Django 5.2 on 2025-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0002_alter_ouruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
