# Generated by Django 5.2 on 2025-05-07 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0002_rename_end_date_task_due_date_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_date_creation',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
