# Generated by Django 5.2 on 2025-05-15 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0003_ouruser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='account_date_creation',
            field=models.DateField(default=datetime.date(2025, 5, 15)),
        ),
    ]
