# Generated by Django 5.2 on 2025-05-15 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0004_alter_ouruser_account_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='account_date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
