# Generated by Django 5.2 on 2025-05-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEmumbaTrainingApplication', '0005_alter_ouruser_account_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
    ]
